export default {
  TEXT_BAR_WIDTH: 400,
  TEXT_NAV_WIDTH: 20,
  CANVAS_BAR_WIDTH: 240,
  TEXT_SELECT_COLOR: '#ddd',
  TEXT_INACTIVE_COLOR: '#eee',
  FILTER_PANEL_WIDTH: 240,
  FILTER_PANEL_HEIGHT: 120,
  ANNOTATION_RADIUS_MIN: 2,
  ANNOTATION_RADIUS_MAX: 25,
  ANNOTATION_SPACE: 2,
  ANNOTATION_PROPERTIES: {
    Sicher: 'certainty',
    Wichtig: 'importance',
    catma_displaycolor: 'color',
    catma_markupauthor: 'author',
  },
  CANVAS_MARGIN: 20,
  LAYOUT_DEFAULT: 'scatterplot',
};
